; alert-triage.iss - Inno Setup script for the Windows installer.
;
; WHAT INNO SETUP IS
; ------------------
; A free installer compiler. `ISCC.exe alert-triage.iss` reads this script,
; compresses every file listed in [Files] into a single self-extracting
; setup.exe, and embeds a wizard that writes those files to a chosen directory,
; creates Start Menu shortcuts, registers an entry in Apps & Features, and
; generates an uninstaller.
;
; WHY A SCRIPT AND NOT A GUI TOOL: the same reason this project has a checked-in
; PyInstaller .spec instead of a long command line. The build configuration is
; source - reviewable in a diff, reproducible on another machine, and the only
; place the packaging decisions live.
;
; WHAT AN INSTALLER BUYS OVER "unzip this folder"
; -----------------------------------------------
;   * a chosen install location, with the app working from wherever it lands
;   * Start Menu (and optional Desktop) shortcuts
;   * an optional PATH entry, so `triage` is a command
;   * an entry in Settings > Apps, which is where users look to remove software
;   * an uninstaller that removes exactly what was installed
; None of that is possible with a zip, and the previous artifact - a 47 MB
; PyInstaller .exe - additionally required Docker Desktop to be installed and
; running before it could do anything. This installer needs no prerequisites at
; all: it ships its own Python and its own embedding model.
;
; THE THREE TIERS
; ---------------
; Inno distinguishes TYPES from COMPONENTS, and the difference is the whole
; mechanism here:
;   * a COMPONENT is a selectable chunk of files ("the Qt GUI", "the pipeline")
;   * a TYPE is a named PRESET of components ("Desktop app", "Thin client")
; The user picks a Type on the Select Components page; Inno ticks the matching
; components; a user who wants something else picks Custom. So ONE payload is
; built and packed, and the tiers are file-group OMISSIONS at install time -
; not three separate builds. Building three payloads would mean packing PySide6
; twice and torch twice for a ~4 GB installer.
;
; Measured tier sizes (see packaging/README.md for the component breakdown):
;   Desktop app      2022 MB   core + gui + pipeline
;   Command line     1398 MB   core + pipeline        (-31%, drops Qt)
;   Thin client       682 MB   core + gui             (-66%, drops the ML stack)
; The pipeline is the single biggest cost at 1340 MB, but Qt is not small
; either at 624 MB - the planning estimate that dropping the GUI would save
; only ~10% was wrong, because the PySide6 wheels unpack to about four times
; their download size.
;
; BUILD ORDER
;   1. powershell -ExecutionPolicy Bypass -File packaging\build_payload.ps1
;   2. "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" packaging\alert-triage.iss
; Step 1 is what generates version.iss and components.iss, both #include'd
; below; this script does not compile without it. See packaging/README.md.

; Generated by build_payload.ps1 from pyproject.toml, so the installer version
; can never disagree with the app version. That matters more here than in most
; projects: app_version is an ENFORCED staleness-fingerprint field (PLAN.md
; Phase 9), so an installer labelled 0.4.0 that installs 0.5.0 code would
; refuse stores built by "the same" version with a baffling error.
; Defines AppVersion and Payload. Both are generated rather than written here:
; the version so it cannot disagree with the installed code, and the payload
; location so the -PayloadDir build option reaches the compiler.
#include "..\build\installer\version.iss"

#define AppName        "Alert Triage RAG"
#define AppPublisher   "Mario"
#define AppURL         "https://github.com/mario0111/alert-triage-rag"

[Setup]
; AppId is the IDENTITY of the application to Windows - the key under which the
; uninstall entry is registered. It must stay CONSTANT across versions: change
; it and an upgrade installs alongside the old copy instead of replacing it,
; leaving two entries in Apps & Features and two copies of a 1.6 GB payload.
AppId={{7E4A9C31-5B2D-4E86-9F13-2C6A8D0B4E57}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
VersionInfoVersion={#AppVersion}

; PER-USER INSTALL, deliberately. `lowest` means the installer never requests
; elevation, so there is no UAC prompt and {autopf} resolves to
; %LOCALAPPDATA%\Programs instead of C:\Program Files. Reasons:
;   * nothing here needs machine-wide state - no services, no drivers, no
;     shared registry, and the app's data dir is already per-user
;     (%LOCALAPPDATA%\alert-triage-rag, resolved by platformdirs in paths.py)
;   * an unsigned installer asking for admin is the worst of both worlds
;   * a per-user install can be removed by the user who made it
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
PrivilegesRequired=lowest
AllowNoIcons=yes

; The payload ships 64-bit CPython and 64-bit native wheels (torch, chromadb's
; hnswlib, onnxruntime), so a 32-bit machine must be refused UP FRONT with a
; clear message rather than at the first `import torch`.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

; Tells Inno to broadcast WM_SETTINGCHANGE after installing. Without it the
; PATH entry written below is invisible to already-open Explorer/terminal
; sessions until the user logs out.
ChangesEnvironment=yes

; SourceDir is the base for relative Source/OutputDir paths. Pointing it at the
; repo root is not cosmetic: it removes "packaging\..\" from the absolute path
; ISCC builds for every one of ~3000 payload files. Windows' MAX_PATH is 260
; characters and torch's dist-info carries vendored licence texts nested ten
; directories deep, so those 13 characters are the difference between a
; successful compile and ISCC aborting with "The system cannot find the path
; specified". build_payload.ps1 checks the real budget and fails loudly.
SourceDir=..
OutputDir=dist
OutputBaseFilename=alert-triage-rag-{#AppVersion}-setup
; lzma2/max is the best ratio Inno offers, which matters on a ~1.7 GB payload.
;
; SolidCompression is deliberately OFF. Solid mode compresses every file as one
; continuous stream, which compresses better - but to extract any file the
; installer must decompress everything before it. A thin-client install would
; have to stream ~1.7 GB to write ~300 MB, punishing precisely the tier the
; components exist to make cheap. Per-file compression keeps a partial install
; proportional to what it actually installs.
Compression=lzma2/max
SolidCompression=no
WizardStyle=modern
UninstallDisplayName={#AppName} {#AppVersion}
UninstallDisplayIcon={app}\python\pythonw.exe
; The payload contains tens of thousands of small files (site-packages), so the
; wizard's per-file label would otherwise be the slowest part of the install.
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
; The presets shown on the Select Components page. `iscustom` marks the entry
; Inno switches to automatically when the user ticks a combination that matches
; no preset - without it, hand-picking components silently snaps back.
Name: "desktop"; Description: "Desktop app - native window, full local pipeline (recommended)"
Name: "cli";     Description: "Command line only - full local pipeline, no GUI"
Name: "thin";    Description: "Thin client - GUI only, connects to a remote or Docker API"
Name: "custom";  Description: "Custom installation"; Flags: iscustom

[Components]
; `fixed` = always installed, cannot be unticked. Core is the embeddable
; CPython plus the triage package itself; every tier needs it.
Name: "core";     Description: "Core files (bundled Python runtime + triage package)"; \
                  Types: desktop cli thin custom; Flags: fixed
Name: "gui";      Description: "Desktop app (Qt / PySide6)"; \
                  Types: desktop thin
Name: "pipeline"; Description: "Local triage pipeline + bundled embedding model (runs offline, no Docker)"; \
                  Types: desktop cli

[Files]
; --- The interpreter -------------------------------------------------------
; NOT recursive on purpose: this takes only the root of the embeddable
; distribution (python.exe, pythonw.exe, python311.dll, python311.zip holding
; the stdlib, the .pyd extension modules, vcruntime140.dll, and the
; python311._pth that build_payload.ps1 rewrote). Lib\site-packages is handled
; entirely by the generated manifest below, because that is where the
; per-component split lives.
Source: "{#Payload}\python\*"; DestDir: "{app}\python"; Flags: ignoreversion; Components: core

; --- site-packages, split by component -------------------------------------
; GENERATED by build_payload.ps1: one line per top-level site-packages entry,
; tagged core / gui / pipeline. The split is COMPUTED by diffing what pip
; installs for the wheel alone, for PySide6 alone, and for the full payload -
; never hand-maintained, because a hand-written list would silently rot the
; first time a transitive dependency appeared or vanished.
#include "..\build\installer\components.iss"

; --- The bundled embedding model -------------------------------------------
; bge-small-en-v1.5, ~130 MB, in Hugging Face cache layout. Found at runtime by
; sitecustomize.py, which sets HF_HOME relative to its own location - so this
; works wherever the user chose to install. Pipeline-only: the thin client
; never embeds anything locally.
Source: "{#Payload}\models\*"; DestDir: "{app}\models"; \
        Flags: ignoreversion recursesubdirs createallsubdirs; Components: pipeline

; --- The CLI shim ----------------------------------------------------------
; Pipeline-only, and that is a real constraint rather than tidiness:
; triage/cli.py imports ingest, query and serve at module level, so the `triage`
; command needs torch. A thin-client install that put a broken `triage` on PATH
; would be worse than not having one. (Making cli.py lazy-import its
; subcommands would lift this restriction - a worthwhile separate change.)
Source: "{#Payload}\triage.cmd"; DestDir: "{app}"; Flags: ignoreversion; Components: pipeline

Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme; Components: core

[Icons]
; The GUI shortcut targets pythonw.exe - the console-less interpreter - so no
; black window appears behind the Qt window. It runs `-m triage.desktop_launch`
; rather than a Scripts\*.exe console shim, because Windows Smart App Control
; blocks those shims outright.
;
; TWO variants, selected by a boolean component expression. With the pipeline
; installed, the app may autostart its own backend: triage/backend.py probes
; /health and, finding nothing, spawns `sys.executable -m triage.serve` - which
; here is the bundled pythonw.exe, whose environment HAS the pipeline. No
; Docker involved. Without the pipeline that spawn would die on `import torch`
; and be misreported as a stale store, so the thin tier passes --no-autostart
; and simply reports that it cannot reach the configured API.
Name: "{group}\{#AppName}"; Filename: "{app}\python\pythonw.exe"; \
      Parameters: "-m triage.desktop_launch"; WorkingDir: "{app}"; \
      Comment: "Triage an alert (starts a local backend if none is running)"; \
      Components: gui and pipeline
Name: "{group}\{#AppName}"; Filename: "{app}\python\pythonw.exe"; \
      Parameters: "-m triage.desktop_launch --no-autostart"; WorkingDir: "{app}"; \
      Comment: "Triage an alert against a remote or containerised API"; \
      Components: gui and not pipeline

; Ingest is an EXPLICIT one-off, never automatic - the same decision the Docker
; path makes (PLAN.md Phase 10). Auto-ingesting on install would bury a
; multi-minute, network-touching corpus build inside "installing", and worse,
; it would MUTE the staleness fingerprint: the loud "re-run triage ingest"
; refusal would become a silent self-heal. So it gets a visible shortcut.
Name: "{group}\Build the triage store (run this first)"; \
      Filename: "{app}\python\python.exe"; Parameters: "-m triage.ingest"; \
      WorkingDir: "{app}"; \
      Comment: "Download MITRE ATT&CK and build the local vector store"; \
      Components: pipeline

; A console pre-loaded with the app on PATH, for users who did not take the
; PATH task (or want it without a global change).
Name: "{group}\Triage command prompt"; Filename: "{cmd}"; \
      Parameters: "/K ""set PATH={app};%PATH%"""; WorkingDir: "{app}"; \
      Comment: "Command prompt with the `triage` command available"; \
      Components: pipeline

Name: "{autodesktop}\{#AppName}"; Filename: "{app}\python\pythonw.exe"; \
      Parameters: "-m triage.desktop_launch"; WorkingDir: "{app}"; \
      Components: gui and pipeline; Tasks: desktopicon
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\python\pythonw.exe"; \
      Parameters: "-m triage.desktop_launch --no-autostart"; WorkingDir: "{app}"; \
      Components: gui and not pipeline; Tasks: desktopicon

[Tasks]
; Optional, and unticked by default: modifying PATH is a change to the user's
; environment, so it should be a decision, not a side effect. Offered only with
; the pipeline component, for the same reason the shim is pipeline-only.
Name: "addtopath"; Description: "Add the &triage command to my PATH"; \
      Components: pipeline; Flags: unchecked
Name: "desktopicon"; Description: "Create a &desktop shortcut"; \
      Components: gui; Flags: unchecked

[Registry]
; HKA ("auto") resolves to HKEY_CURRENT_USER here because PrivilegesRequired is
; `lowest` - a per-user PATH, matching the per-user install.
;   * {olddata} is the existing value, so this APPENDS rather than replaces -
;     getting this wrong is the classic installer bug that erases a user's PATH.
;   * preservestringtype keeps REG_EXPAND_SZ as REG_EXPAND_SZ, so entries like
;     %USERPROFILE%\bin elsewhere in the value keep expanding.
;   * Check: NeedsAddPath prevents a duplicate entry when reinstalling.
Root: HKA; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; \
      ValueData: "{olddata};{app}"; Tasks: addtopath; \
      Check: NeedsAddPath(ExpandConstant('{app}')); Flags: preservestringtype

[Run]
; postinstall = a checkbox on the final wizard page. Both unticked: a
; multi-minute download should be the user's explicit choice, and so should
; launching an app that will start a backend.
Filename: "{app}\python\python.exe"; Parameters: "-m triage.ingest"; \
      WorkingDir: "{app}"; \
      Description: "Build the triage store now (downloads ~51 MB, takes a few minutes)"; \
      Flags: postinstall skipifsilent unchecked; Components: pipeline
Filename: "{app}\python\pythonw.exe"; Parameters: "-m triage.desktop_launch"; \
      WorkingDir: "{app}"; Description: "Launch {#AppName}"; \
      Flags: postinstall nowait skipifsilent unchecked; Components: gui and pipeline

[UninstallDelete]
; Inno removes what it installed. Python creates __pycache__ directories all
; over site-packages the first time each module is imported, and Hugging Face
; writes lock files under the model cache - none of which the installer put
; there, so without these entries an "uninstall" would leave hundreds of MB and
; a folder that looks like a failed removal.
Type: filesandordirs; Name: "{app}\python\Lib\site-packages"
Type: filesandordirs; Name: "{app}\models"
Type: dirifempty;     Name: "{app}\python\Lib"
Type: dirifempty;     Name: "{app}\python"
Type: dirifempty;     Name: "{app}"

[Code]
const
  EnvironmentKey = 'Environment';

// NOTE ON COMMENT STYLE: this section is Pascal, where { ... } is a comment
// delimiter - and Inno's own constants are written {app}, {group}, {olddata}.
// A brace comment mentioning one would therefore END at that constant's
// closing brace and spill the rest of the sentence into the compiler as code.
// So [Code] uses // line comments throughout.

// True when the app directory is not already on the user's PATH. Both sides
// are wrapped in separators so a substring match cannot produce a false
// positive (e.g. "C:\Apps\Triage" appearing inside "C:\Apps\Triage2").
function NeedsAddPath(Param: string): Boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;
end;

// Remove the app directory from PATH on uninstall. Inno appends the entry for
// us but has no matching "unappend", so leaving this out would strand a dead
// directory on the user's PATH forever. Rebuilt entry-by-entry rather than by
// string surgery: deleting a substring has to reason about whether the
// separator before or after it belongs to the neighbour, which is exactly how
// these routines end up corrupting a PATH.
procedure RemoveFromPath(Dir: string);
var
  Path, NewPath, Part: string;
  P: Integer;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', Path) then
    exit;
  if Pos(';' + Uppercase(Dir) + ';', ';' + Uppercase(Path) + ';') = 0 then
    exit;

  NewPath := '';
  Path := Path + ';';
  repeat
    P := Pos(';', Path);
    Part := Trim(Copy(Path, 1, P - 1));
    Delete(Path, 1, P);
    if (Part <> '') and (CompareText(Part, Dir) <> 0) then
    begin
      if NewPath <> '' then
        NewPath := NewPath + ';';
      NewPath := NewPath + Part;
    end;
  until Path = '';

  RegWriteExpandStringValue(HKEY_CURRENT_USER, EnvironmentKey, 'Path', NewPath);
end;

// Refuse an install folder long enough to push the deepest payload file past
// Windows' 260-character path limit. MaxAppDirLen is MEASURED at build time
// (259 minus the longest relative path in the payload) and written into
// version.iss, so it tracks the payload instead of being a guess that rots.
//
// The deep files are vendored third-party licence texts inside torch's
// dist-info - ten directories of nesting, and not removable, since they are
// how a redistribution satisfies the notice requirements of the libraries
// torch bundles. Without this check the failure is silent and much later: a
// truncated path, a file that "does not exist", and an app that half works.
function DirTooLongMessage(): String;
begin
  Result := 'The installation folder path is too long.' + #13#10 + #13#10 +
            'Windows limits a full file path to 260 characters, and this ' +
            'application contains some very deeply nested files (bundled ' +
            'third-party licence texts inside PyTorch).' + #13#10 + #13#10 +
            'Please choose a folder of at most {#MaxAppDirLen} characters. ' +
            'The current one is ' + IntToStr(Length(WizardDirValue)) + '.';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CurPageID = wpSelectDir) and (Length(WizardDirValue) > {#MaxAppDirLen}) then
  begin
    MsgBox(DirTooLongMessage(), mbError, MB_OK);
    Result := False;
  end;
end;

// The same check again, because NextButtonClick never fires during a silent
// install (/SILENT, /VERYSILENT) - there are no wizard pages to click through.
// PrepareToInstall runs in every mode, and returning a non-empty string aborts
// with that message. Without this, `setup.exe /VERYSILENT /DIR=<long path>`
// would produce a silently half-written install, which is precisely the
// scenario an automated deployment would hit and not notice.
function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  if Length(WizardDirValue) > {#MaxAppDirLen} then
    Result := DirTooLongMessage();
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: string;
begin
  if CurUninstallStep = usUninstall then
    RemoveFromPath(ExpandConstant('{app}'));

  // The app's DATA deliberately does not live under the install directory:
  // paths.py resolves it with platformdirs to %LOCALAPPDATA%\alert-triage-rag,
  // so the downloaded ATT&CK bundle and the Chroma store survive an upgrade.
  // That also means a plain uninstall leaves ~700 MB behind, which is normal
  // for a CLI app but surprising for something with an Apps & Features entry.
  // So: offer, default to No, and never delete silently - a reinstall would
  // otherwise have to re-download and re-embed the whole corpus.
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{localappdata}\alert-triage-rag');
    if DirExists(DataDir) then
    begin
      // SuppressibleMsgBox, NOT MsgBox - and this is a bug found by actually
      // running an unattended uninstall. During a silent uninstall
      // (/VERYSILENT /SUPPRESSMSGBOXES) there is nobody to answer, so Inno
      // answers for us. Plain MsgBox returns the AFFIRMATIVE default and
      // ignores MB_DEFBUTTON2 - so the "default to No" intent was silently
      // inverted and an automated uninstall DELETED the user's vector store
      // and the 53 MB ATT&CK bundle, minutes of rebuilding, with no prompt.
      // SuppressibleMsgBox takes the silent answer as an explicit argument,
      // which is the only way to make "if in doubt, keep the data" hold in
      // both modes. MB_DEFBUTTON2 is kept for the interactive case.
      if SuppressibleMsgBox('Also delete the triage data directory?' + #13#10 + #13#10 +
                DataDir + #13#10 + #13#10 +
                'It holds the downloaded MITRE ATT&CK bundle and the vector ' +
                'store (typically around 700 MB). Keep it if you plan to ' +
                'reinstall - rebuilding it means downloading and re-embedding ' +
                'the whole corpus.',
                mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
